### ISSUE TITLE
update-system shouldn't use docker interface for default urls

### ISSUE THREAD

**Issue by logikal** [StackStorm/puppet-st2#144]
Initial set up using the all in one installer uses the correct addresses for urls. If you later run update-system without answers in answers.yaml for those values, it will set them to the docker interface. Pretty sure we don't want that.

Note that I've only run into this when I have _not_ run the webgui setup (because I like to automate my automation).

relevant puppet logs:

```
...
Notice: /Stage[main]/St2::Helper::Auth_manager/Ini_setting[auth_api_url]/value: value changed 'https://10.0.2.15:9101' to 'https://172.17.42.1:9101'
...
Notice: /Stage[main]/St2::Profile::Client/St2::Client::Settings[root]/Ini_setting[root-st2_cli_api_url]/value: value changed 'https://10.0.2.15/api' to 'https://172.17.42.1/api'
Notice: /Stage[main]/St2::Profile::Client/St2::Client::Settings[root]/Ini_setting[root-st2_cli_auth_url]/value: value changed 'https://10.0.2.15/auth' to 'https://172.17.42.1/auth'
...
```

**Comment by nmaludy** [comment]
@logikal There have been a lot of changes that have happened as a result of #172 , can you please try this again with version `1.0.0-beta`?

Thanks,
Nick

**Comment by nmaludy** [comment]
@logikal if you run into this issue again with the latest version please create a new issue.

Thanks,
Nick
