### ISSUE TITLE
Add support for URLs in st2chatops.env

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/puppet-st2#199]
Currently in `st2::profile::chatops` we can configure most settings in `st2chatops.env` but the URLs for things like the API, auth and web are still hard coded.

Need to figure out a good way to make the default still point to `localhost` and then allow them to be overridden when there are complex deployments in place.

**Comment by armab** [comment]
I think the best way for configuration management is to provide env variables in `/etc/sysconfig/st2chatops` and `/etc/sysconfig/st2chatops` which `st2chatops` will take as a priority over `st2chatops.env` settings.

See https://github.com/StackStorm/st2chatops/issues/50 for more explanation.

**Comment by nmaludy** [comment]
Good idea!
