### ISSUE TITLE
Pack resource should support subtree flag when calling Pack Install action

### ISSUE THREAD

**Issue by joecise** [StackStorm/puppet-st2#21]
Once the install action-chain is updated to support the subtree flag (https://github.com/StackStorm/st2/issues/1616) then the st2::pack resources (https://github.com/StackStorm/puppet-st2/blob/master/manifests/pack.pp) should be updated to support it.

**Comment by jfryman** [comment]
Updated to 0.4.5 version on the forge. https://forge.puppetlabs.com/stackstorm/st2/readme Will be usable once https://github.com/StackStorm/st2/issues/1616 is addressed.

**Comment by joecise** [comment]
Thanks @jfryman!
