### ISSUE TITLE
Add support for Ubuntu 18.04

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/puppet-st2#213]
Ubuntu 18.04 is out now. We should look into supporting it in Puppet.

Will need to wait for support from StackStorm/st2 core and StackStorm/st2packaging

**Comment by armab** [comment]
From @LindsayHill message in #community:

> Current thinking is along the lines of:
>- Add u18 support in 3-6 months
>- *drop* u14 support next April, when it goes end of LTS
>- Aim to add RHEL 8.x support when 8.1 ships
>- Drop RHEL 6.x at that time
>There is also related work going on with adding more Py3 support, but we don't have a firm date for dropping py2.7

So no immediate `U18` support, but highly likely we'll add it during the next half of the year.
