### ISSUE TITLE
Pack resource should support register option when calling Pack Install action

### ISSUE THREAD

**Issue by joecise** [StackStorm/puppet-st2#22]
The Pack Install action-chain supports the register option (https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/install.meta.yaml#L22), and I would like to be able to use it from the Pack resource (https://github.com/StackStorm/puppet-st2/blob/master/manifests/pack.pp).

**Comment by jfryman** [comment]
Puppet module 0.4.5 released to the forge. https://forge.puppetlabs.com/stackstorm/st2/readme

**Comment by joecise** [comment]
Thanks!
