### ISSUE TITLE
Switch from Kitchen to Litmus for integration testing

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/puppet-st2#284]
In order to get this module approved, the Puppet team would like us to use Litmus for integration testing: https://github.com/puppetlabs/puppet_litmus

There are also some example travis configs here: https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.travis.yml.erb#L112-L130

**Comment by rush-skills** [comment]
@nmaludy Is this something that still needs to be done? Does it help enhance our CI pipeline anyhow?

**Comment by nmaludy** [comment]
@rush-skills No, i spent over a month trying to get this to work and the StackStorm containers use a different tagging scheme than the rest of the world, so the code inside Litmus doesn't work correctly when trying to test our images. I'm going to close this issue and just stick with Kitchen.
