### ISSUE TITLE
Configure Github Actions to report CI failures to Slack

### ISSUE THREAD

**Issue by armab** [StackStorm/puppet-st2#346]
We have `#puppet` Slack community channel.
It would be nice to configure Slack alerts in case of CI failure in the master branch to bring more attention and ensure the Puppet CI is always green.
We do this for other repos as well, you can check stackstorm/st2 for examples to follow.

**Comment by rush-skills** [comment]
https://github.com/StackStorm/puppet-st2/pull/348/commits/5505f3e222fa752a0675b0b97682e0aca35aab83 in https://github.com/StackStorm/puppet-st2/pull/348 should fix this, once merged

**Comment by armab** [comment]
Nice!
Could we perhaps extract it in a separate PR? that would make it easier to review and merge ASAP. Also good for history.
