### ISSUE TITLE
Avoid hard-coding git repo URLs

### ISSUE THREAD

**Issue by Undeterminant** [StackStorm/puppet-st2#80]
It would be a huge benefit to this module to be able to specify a source and version for StackStorm on the installation that can be cloned and distributed on systems which aren't connected to the outside world. Right now, configuration on that end requires cloning an internal repo, which isn't as desired.

If we could have the ability to install StackStorm via puppet via a packaged-up DEB/RPM, it would be really helpful.

**Comment by jfryman** [comment]
Thanks for the feedback!

We certainly understand where you are coming from. We have team members working on fully packaged DEBs and RPMs and these should be released very soon! (Weeks)

Stay tuned! We'll update this issue and let you know when this is done.

**Comment by Undeterminant** [comment]
Thank you!

**Comment by armab** [comment]
Closing as outdated or even implemented.
We're using deb/rpm packages and don't `git clone` st2 or st2mistral anymore.
